apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker # aqui tambem pode usar app: worker, é livre
  template:
    metadata:
      labels:
        component: worker # aqui tambem pode usar app: worker, é livre, tem que casar com o de cima
    spec:
      containers:
        - name: worker # aqui pode ser qualquer nome
          image: stephengrider/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
